name: mrc_madad_3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  provider: ^6.0.1
  google_sign_in: ^5.1.0
  google_fonts: ^2.1.0
  webview_flutter: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  dio: ^4.0.0
  lottie: ^1.2.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  animated_text_kit: ^4.2.1
  path: ^1.8.0
  path_provider: ^2.0.5
  image_picker: ^0.8.4+3
  uuid: ^3.0.5
  flutter_sound: ^8.4.1+1
  permission_handler: ^8.2.5
  assets_audio_player: ^3.0.3+6
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  share_plus: ^3.0.4
  clay_containers: ^0.3.2
  font_awesome_flutter: ^9.2.0
  just_audio: ^0.9.17
  audio_video_progress_bar: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/fonts/
    - assets/svgs/
    - assets/flags/

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/Brandon_bld.otf
        - asset: assets/fonts/Brandon_bld_it.otf
        - asset: assets/fonts/Brandon_blk.otf
        - asset: assets/fonts/Brandon_light.otf
        - asset: assets/fonts/Brandon_med.otf
        - asset: assets/fonts/Brandon_reg.otf
        - asset: assets/fonts/Brandon_thin.otf
    - family: Franklin Gothic
      fonts:
        - asset: assets/fonts/Franklin_Gothic_Condensed.ttf
        - asset: assets/fonts/FranklinGothic.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Black.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Eczar
      fonts:
        - asset: assets/fonts/Eczar-Regular.ttf
        - asset: assets/fonts/Eczar-Medium.ttf
    - family: Ramabhadra
      fonts:
        - asset: assets/fonts/Ramabhadra-Regular.ttf
    - family: Noto Serif Telugu
      fonts:
        - asset: assets/fonts/NotoSerifTelugu-Regular.ttf
    - family: Hind Madurai
      fonts:
        - asset: assets/fonts/HindMadurai-Regular.ttf
        - asset: assets/fonts/HindMadurai-SemiBold.ttf
    - family: Noto Serif Malayalam
      fonts:
        - asset: assets/fonts/NotoSerifMalayalam-Regular.ttf
    - family: Noto Serif Kannada
      fonts:
        - asset: assets/fonts/NotoSerifKannada-Regular.ttf
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: Abril Fatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
